version: "3"

services:
  nodejs:
    build:
      context: .
    container_name: api-geek
    image: api-geek
    restart: always
    env_file:
      - .env
    ports:
    - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:12.3-alpine
    container_name: postgres-node
    volumes:
    - ./sql/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: geek_commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
